# Generated by Django 2.2.2 on 2019-06-07 11:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20190607_1655'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userType',
            new_name='usersdb',
        ),
    ]
