# Generated by Django 2.2.2 on 2019-06-07 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190607_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Usersdb'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Courses')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Usersdb')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Courses')),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField()),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=50)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Usersdb')),
            ],
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=50)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Subjects')),
            ],
        ),
    ]
