# Generated by Django 2.2.2 on 2019-06-07 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190608_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Usersdb'),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Usersdb'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Usersdb'),
        ),
    ]
