# Generated by Django 2.2.2 on 2019-06-18 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190619_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Usersdb'),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Usersdb'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Courses'),
        ),
    ]
