# Generated by Django 2.2.2 on 2019-06-19 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_subjects_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
    ]
