# Generated by Django 2.2.2 on 2019-06-24 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20190624_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exams',
            name='student_name',
        ),
    ]
